/* 
	IMG Light Develop by BlocksBerg (www.BlocksBerg.in.th) © BlocksBerg. All right reserved.
	Download Last version at www.BlocksBerg.in.th/plugin/imglight
*/

var bg_color_img_light = 'rgba(0,0,0,0.9)';		//Change Background Color of div IMG Light
var allow_hide_scroll_img_light = 'no';			//Allow Hide and Fixed scroll, 'yes' or 'no'
var use_fade_inout_img_light = 'yes';			//Use Fade in and Fade out, 'yes' or 'no'
var speed_img_light = 0.08;						//Change Speed Fade in and Fade out Between 0 and 1, 1 is Fastest
var z_index_dv_img_light = 999;					//Change z-index of div IMG Light	
var vopa_img_light,idpopup_img_light;
window.onload=function(){var crtdv_IMG_Light=document.createElement('div');crtdv_IMG_Light.id='IMG-Light';document.getElementsByTagName('body')[0].appendChild(crtdv_IMG_Light);idpopup_img_light=document.getElementById("IMG-Light");idpopup_img_light.style.top=0;idpopup_img_light.style.left=0;idpopup_img_light.style.opacity=0;idpopup_img_light.style.width='100%';idpopup_img_light.style.height='100%';idpopup_img_light.style.display='none';idpopup_img_light.style.position='fixed';idpopup_img_light.style.cursor='pointer';idpopup_img_light.style.textAlign='center';idpopup_img_light.style.zIndex=z_index_dv_img_light;idpopup_img_light.style.backgroundColor=bg_color_img_light;};function img_light(namepic_img_light){vopa_img_light=0;var hwin_img_light=window.innerHeight;var wwin_img_light=window.innerWidth;var himg_img_light,padtop_img_light,idfadein_img_light;var img_img_light=new Image();img_img_light.src=namepic_img_light;img_img_light.onload=function(){himg_img_light=img_img_light.height;wimg_img_light=img_img_light.width;idpopup_img_light.innerHTML='<img src='+namepic_img_light+'>';if(wimg_img_light>wwin_img_light){idpopup_img_light.getElementsByTagName('img')[0].style.width='90%';}else if(himg_img_light>hwin_img_light){idpopup_img_light.getElementsByTagName('img')[0].style.height='90%';himg_img_light=hwin_img_light*90/100;}if(himg_img_light<hwin_img_light){padtop_img_light=(hwin_img_light/2)-(himg_img_light/2);idpopup_img_light.style.paddingTop=padtop_img_light+'px';}else{idpopup_img_light.style.paddingTop='0px';}if(allow_hide_scroll_img_light=='yes'){document.body.style.overflow='hidden';}idpopup_img_light.style.display='block';};if(use_fade_inout_img_light=='yes'){idfadein_img_light=setInterval(function(){if(vopa_img_light<=1.1){idpopup_img_light.style.opacity=vopa_img_light;vopa_img_light+=speed_img_light;}else{idpopup_img_light.style.opacity=1;clearInterval(idfadein_img_light);}},10)}else{idpopup_img_light.style.opacity=1;}idpopup_img_light.onclick=function(){if(use_fade_inout_img_light=='yes'){var idfadeout_img_light=setInterval(function(){if(vopa_img_light>=0){idpopup_img_light.style.opacity=vopa_img_light;vopa_img_light-=speed_img_light;}else{idpopup_img_light.style.opacity=0;clearInterval(idfadeout_img_light);idpopup_img_light.style.display='none';idpopup_img_light.innerHTML='';document.body.style.overflow='visible';vopa_img_light=0;}},10);}else{idpopup_img_light.style.opacity=0;idpopup_img_light.style.display='none';idpopup_img_light.innerHTML='';document.body.style.overflow='visible';}}}